# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [3]:
print("Hello World! We are learning deep learning.")

Hello World!

In [4]:

import pandas as pd

customerData = pd.read_csv(r"C:\Users\tcetiner\PycharmProjects\CustomerChurnForecasting\data\customer-churn.csv")
customerData.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:

from sklearn.model_selection import train_test_split

churn = customerData["Churn"].map({"Yes": 1, "No": 0})
print(churn.head())

features = customerData.drop(["Churn", "customerID"], axis=1)


features = pd.get_dummies(features,drop_first=True)
print(features.head());

X_train, X_test, y_train, y_test = train_test_split(features, churn, test_size=0.2)
print("Features printing")
features.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64
   SeniorCitizen  tenure  MonthlyCharges  gender_Male  Partner_Yes  \
0              0       1           29.85        False         True
1              0      34           56.95         True        False
2              0       2           53.85         True        False
3              0      45           42.30         True        False
4              0       2           70.70        False        False

   Dependents_Yes  PhoneService_Yes  MultipleLines_No phone service  \
0           False             False                            True
1           False              True                           False
2           False              True                           False
3           False             False                            True
4           False              True                           False

   MultipleLines_Yes  InternetService_Fiber optic  ...  TotalCharges_995.35  \
0              False                        False  ...                False
1              False                        False  ...                False
2              False                        False  ...                False
3              False                        False  ...                False
4              False                         True  ...                False

   TotalCharges_996.45  TotalCharges_996.85  TotalCharges_996.95  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                False                False

   TotalCharges_997.65  TotalCharges_997.75  TotalCharges_998.1  \
0                False                False               False
1                False                False               False
2                False                False               False
3                False                False               False
4                False                False               False

   TotalCharges_999.45  TotalCharges_999.8  TotalCharges_999.9
0                False               False               False
1                False               False               False
2                False               False               False
3                False               False               False
4                False               False               False

[5 rows x 6559 columns]
Features printing

,SeniorCitizen,tenure,MonthlyCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,TotalCharges_995.35,TotalCharges_996.45,TotalCharges_996.85,TotalCharges_996.95,TotalCharges_997.65,TotalCharges_997.75,TotalCharges_998.1,TotalCharges_999.45,TotalCharges_999.8,TotalCharges_999.9
0,0,1,29.85,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0,34,56.95,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,2,53.85,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,45,42.30,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0,2,70.70,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [6]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Printing values")
print(X_train)

Printing values
[[-0.44292025 -0.95430576  1.25632458 ... -0.01332386 -0.01332386
  -0.01332386]
 [-0.44292025 -0.26245196  0.33582073 ... -0.01332386 -0.01332386
  -0.01332386]
 [-0.44292025 -1.27988402  0.31247461 ... -0.01332386 -0.01332386
  -0.01332386]
 ...
 [-0.44292025  1.60962303  1.72324683 ... -0.01332386 -0.01332386
  -0.01332386]
 [-0.44292025 -1.03570033 -0.87984469 ... -0.01332386 -0.01332386
  -0.01332386]
 [-0.44292025 -0.38454381 -1.48350846 ... -0.01332386 -0.01332386
  -0.01332386]]

In [9]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),
    layers.Dense(32, activation="relu"),
    layers.Dense(16, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",  # weil sigmoid → Binärklassifikation
    metrics=["accuracy"]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)


loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7105 - loss: 0.5623 - val_accuracy: 0.7578 - val_loss: 0.4971
Epoch 2/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8982 - loss: 0.2683 - val_accuracy: 0.7649 - val_loss: 0.4860
Epoch 3/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9714 - loss: 0.0911 - val_accuracy: 0.7489 - val_loss: 0.5209
Epoch 4/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9807 - loss: 0.0470 - val_accuracy: 0.7391 - val_loss: 0.5524
Epoch 5/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9820 - loss: 0.0371 - val_accuracy: 0.7453 - val_loss: 0.5637
Epoch 6/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9825 - loss: 0.0313 - val_accuracy: 0.7311 - val_loss: 0.5996
Epoch 7/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9845 - loss: 0.0276 - val_accuracy: 0.7365 - val_loss: 0.6126
Epoch 8/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9851 - loss: 0.0263 - val_accuracy: 0.7258 - val_loss: 0.6453
Epoch 9/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9849 - loss: 0.0243 - val_accuracy: 0.7294 - val_loss: 0.6604
Epoch 10/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9867 - loss: 0.0236 - val_accuracy: 0.7391 - val_loss: 0.6628
Epoch 11/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9849 - loss: 0.0237 - val_accuracy: 0.7214 - val_loss: 0.7060
Epoch 12/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9885 - loss: 0.0211 - val_accuracy: 0.7338 - val_loss: 0.7119
Epoch 13/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9900 - loss: 0.0203 - val_accuracy: 0.7347 - val_loss: 0.7171
Epoch 14/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9887 - loss: 0.0199 - val_accuracy: 0.7311 - val_loss: 0.7335
Epoch 15/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9880 - loss: 0.0186 - val_accuracy: 0.7249 - val_loss: 0.7929
Epoch 16/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9896 - loss: 0.0186 - val_accuracy: 0.7303 - val_loss: 0.7742
Epoch 17/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9900 - loss: 0.0174 - val_accuracy: 0.7169 - val_loss: 0.8487
Epoch 18/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9902 - loss: 0.0179 - val_accuracy: 0.7391 - val_loss: 0.8191
Epoch 19/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9909 - loss: 0.0169 - val_accuracy: 0.7223 - val_loss: 0.8642
Epoch 20/20
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9907 - loss: 0.0162 - val_accuracy: 0.7285 - val_loss: 0.8849
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7686 - loss: 0.8668
Test Accuracy: 0.7686302065849304